/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opus/include/opus.h"
/* Header for class com_tyjradio_jrdvoicerecorder_utils_OpusUtils */


#ifndef _Included_com_tyjradio_jrdvoicerecorder_utils_OpusUtils
#define _Included_com_tyjradio_jrdvoicerecorder_utils_OpusUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tyjradio_jrdvoicerecorder_utils_OpusUtils
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */


JNIEXPORT jlong JNICALL Java_com_tyjradio_jrdvoicerecorder_utils_OpusUtils_createEncoder
        (JNIEnv *env, jobject thiz, jint sampleRateInHz, jint channelConfig, jint complexity) ;

JNIEXPORT jlong JNICALL Java_com_tyjradio_jrdvoicerecorder_utils_OpusUtils_createDecoder
        (JNIEnv *env, jobject thiz, jint sampleRateInHz, jint channelConfig);

JNIEXPORT jint JNICALL Java_com_tyjradio_jrdvoicerecorder_utils_OpusUtils_encode
        (JNIEnv *env, jobject thiz, jlong pOpusEnc, jshortArray samples, jint offset,jbyteArray bytes);

JNIEXPORT jint JNICALL Java_com_tyjradio_jrdvoicerecorder_utils_OpusUtils_decode
        (JNIEnv *env, jobject thiz, jlong pOpusDec, jbyteArray bytes,jshortArray samples);

JNIEXPORT void JNICALL Java_com_tyjradio_jrdvoicerecorder_utils_OpusUtils_destroyEncoder
        (JNIEnv *env, jobject thiz, jlong pOpusEnc);
JNIEXPORT void JNICALL Java_com_tyjradio_jrdvoicerecorder_utils_OpusUtils_destroyDecoder
        (JNIEnv *env, jobject thiz, jlong pOpusDec);



#ifdef __cplusplus
}
#endif
#endif
